export const LEGAL = {
  tradeName: 'ELEVEN LEASE',
  operatorName: 'DJAFFAR Mehdi',
  legalIdentity: 'DJAFFAR Mehdi – Entrepreneur individuel / micro-entreprise',
  legalForm: 'Entrepreneur individuel / micro-entreprise',
  siren: '931 287 908',
  siret: '931 287 908 00020',
  addressLine1: '60 rue François 1er',
  postalCode: '75008',
  city: 'Paris',
  country: 'France',
  fullAddress: '60 rue François 1er, 75008 Paris',
  domain: 'elevenlease.fr',
  siteUrl: 'https://elevenlease.fr',
  email: 'contact@elevenlease.fr',
  phoneDisplay: '06 38 01 49 86',
  phoneInternational: '+33638014986',
  activity: "Accompagnement commercial, qualification des besoins clients, mise en relation et apport d’affaires dans le secteur automobile.",
  vatRegime: 'Franchise en base de TVA',
  vatInvoiceNotice: 'TVA non applicable, art. 293 B du CGI',
  publicationDirector: 'DJAFFAR Mehdi',
  hosting: {
    name: 'Vercel Inc.',
    address: '340 S Lemon Ave #4133, Walnut, CA 91789, États-Unis',
    url: 'https://vercel.com',
  },
  roleDisclosure: "ELEVEN LEASE réalise un pré-check commercial et met le client en relation avec ses partenaires. ELEVEN LEASE n’accorde aucun financement et ne garantit aucune acceptation. L’étude définitive et la décision appartiennent exclusivement au partenaire sollicité.",
  serviceFeeDisclosure: "La demande en ligne et le pré-check commercial initial sont gratuits. Si un dossier est lancé, le contenu et le prix de la prestation ELEVEN LEASE sont communiqués par écrit au client et acceptés avant le début de la prestation payante. Les honoraires ne deviennent exigibles qu’après l’acceptation définitive du dossier par le partenaire et la réception effective du véhicule par le client.",
} as const;

export const ORGANIZATION_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': `${LEGAL.siteUrl}/#organization`,
  name: LEGAL.tradeName,
  alternateName: 'Eleven Lease',
  legalName: `${LEGAL.operatorName} – Entrepreneur individuel`,
  url: `${LEGAL.siteUrl}/`,
  logo: `${LEGAL.siteUrl}/eleven-lease-logo.png`,
  email: LEGAL.email,
  telephone: LEGAL.phoneInternational,
  description: LEGAL.activity,
  identifier: [
    { '@type': 'PropertyValue', propertyID: 'SIREN', value: LEGAL.siren.replace(/\s/g, '') },
    { '@type': 'PropertyValue', propertyID: 'SIRET', value: LEGAL.siret.replace(/\s/g, '') },
  ],
  address: {
    '@type': 'PostalAddress',
    streetAddress: LEGAL.addressLine1,
    postalCode: LEGAL.postalCode,
    addressLocality: LEGAL.city,
    addressCountry: 'FR',
  },
  founder: {
    '@type': 'Person',
    name: LEGAL.operatorName,
    sameAs: ['https://www.linkedin.com/in/mehdielevenlease/'],
  },
  sameAs: [
    'https://www.instagram.com/elevenlease',
    'https://www.tiktok.com/@elevenlease',
    'https://www.linkedin.com/company/elevenlease/',
  ],
};
